set @userid=14;
delete from video where Author=@userid;
delete from images where Author=@userid;
delete from music where Author=@userid;
delete from lyrics where Author=@userid;
delete from userways where UserId=@userid;
delete usertoband, bands, bandlanguages from usertoband, bands, bandlanguages where usertoband.BandId=bands.Id and bandlanguages.BandId=bands.Id and bands.Leader=@userid;
delete from usertoband where UserId=@userid;
delete from afisha where AuthorId=@userid;
delete from comments;
delete from forum_subj where AuthorId=@userid;
delete from forum where AuthorId=@userid;
delete from looking_band where Creater=@userid;
delete messages, subjects from messages, subjects where messages.SubjId=subjects.Id and messages.FromId=@userid;
delete from news where Author=@userid;
delete from userlanguages where UserId=@userid;
delete from userstyles where UserId=@userid;
delete from userways where UserId=@userid;
delete from userinfo where Id=@userid;
